### ISSUE TITLE
"display: grid" dont works in android/ios

### ISSUE THREAD

**Issue by martudev** [kristerkari/react-native-sass-transformer#126]
I want to implement a .container2 class like this

```scss
.container {
    display: flex;
    width: 100%;
    height: 100%;
}
.container2 {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
}
```

when I import the file and log the styles like this:

```tsx
import styles from './Main.scss';

{...}

<ThemedView style={styles.container}>
	<View style={styles.container2}>
		<Text>example1</Text>
		<Text>example2</Text>
		<Text>example3</Text>
	</View>
</ThemedView>
```

in the output i get this styles
```
{
  container: { display: 'flex', width: '100%', height: '100%' },
  container2: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)' }
}
```

The thing here its that in `StyleSheet.create` the `display` cant be grid, only flex, so my questions here is.. is this supported by this library? or maybe i cant use grid and i have to use flex? maybe there its a posibility to do some merge when i put grid and transform it to grid so in mobile it works?
Thanks for all!
