### ISSUE TITLE
@import Platform specific extensions

### ISSUE THREAD

**Issue by mohammad76** [kristerkari/react-native-sass-transformer#18]
hi , I Want import a scss file to my App.scss using @import with Platform specific extensions.

this is my code 
```
@import "./assets/scss/main";
```

with this code I get error file not exist , but my file is main.android.scss exist.

please help me to use Platform specific extensions with @import

**Comment by kristerkari** [comment]
Which version of this library are you using? The platform specific extensions should work as of version 1.3.0.

One thing that you also need to remember, is that you need to restart the React Native packager if you add new files to the project.

If you have your project/code with the problem available somewhere, I can have a look at it.

**Comment by mohammad76** [comment]
my library version is 1.3.1.

I restart the React Native packager but my code not work again.

how use import ? address the file from project root or not ? with .scss extension or not?

please show me the example. how to use @import with platform specific extensions. thanks

**Comment by kristerkari** [comment]
Thanks for the additional info. 👍 

The imports should work the same way as in normal Sass. 

It might be that there is a bug and it does not work because of that. I will take your example and see if it works for me. I will let you know if I managed to get it work or not.

**Comment by kristerkari** [comment]
@mohammad76 I just tested your example with one of the demo apps and it is working for me. Here's what I did:

`App.js`
```jsx
import test from "./test.scss";
```
```jsx
<Text style={test.foo}>Test</Text>
```
`test.scss`
```scss
@import "./assets/scss/main";
```

`main.android.scss`
```scss
.foo {
  color: #f00;
}
```

When I ran that on Android, the app renders a red text.

**Comment by kristerkari** [comment]
Thanks for the response @mohammad76.

From your example it seems that you might be referencing the relative paths in a wrong way. You are thinking that the import always starts from the root folder.

So, if your `App.scss` is in the `assets/scss`, and inside it you are referencing to `"./assets/scss/main"`, then it tries to find the file from `assets/scss/assets/scss/main.android.scss`.

If `App.scss` and `main.android.scss` are in the same folder then the import should be like this:

```scss
.head {
  color: #333;
  font-family: shabnam;
  text-align: center;
}

.viewbox{
  padding: 10px;
  border: 1px solid #ddd;
  margin: 10px;
  border-radius: 5px;
}

@import "./main";
```

or 

```scss
.head {
  color: #333;
  font-family: shabnam;
  text-align: center;
}

.viewbox{
  padding: 10px;
  border: 1px solid #ddd;
  margin: 10px;
  border-radius: 5px;
}

@import "main";
```
